from src.assignment_three.objective_functions.objective_function_interface import ObjectiveFunctionInterface
from src.assignment_three.objective_functions.truss_objective_function import TrussObjectiveFunction
from src.assignment_three.objective_functions.benchmark_objective_function_interface import BenchmarkObjectiveFunctionInterface
from src.assignment_three.objective_functions.michalewicz_function import MichalewiczFunction2D
